### ISSUE TITLE
Linear Search in java

### ISSUE THREAD

**Issue by DineshaPriyadarshani** [FOSS-UCSC/FOSSALGO#15]
This issues is about linear search in java. https://www.tutorialspoint.com/data_structures_algorithms/linear_search_algorithm.htm

 

- [ ]  Issue title form Algo/DS Name [Language]

- [ ]  I searched or browsed the repo's other issues to ensure this is not a duplicate

- [ ] This Algo/DS is worth to add this repository

- [ ] Assign this issue to me

- [ ] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
@DineshaPriyadarshani please check the 1st factor of your issue.. According to that your name should be like "Linear Search in Java"
