### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by DineshaPriyadarshani** [FOSS-UCSC/FOSSALGO#17]
This issues is about Insertion Sort in java.
 https://www.programiz.com/dsa/insertion-sort

 

- [ ]  Issue title form Algo/DS Name [Language]

- [ ]  I searched or browsed the repo's other issues to ensure this is not a duplicate

- [ ] This Algo/DS is worth to add this repository

- [ ] Assign this issue to me

- [ ] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
@DineshaPriyadarshani rename the issue correctly. check others' issues

**Comment by RavinduSachintha** [comment]
Sorry, now I realized, this is a duplicate issue. @Chathurangi6 has already finished this. If you wish, you can select a different language to implement this rather than Java.
