### ISSUE TITLE
BinarySearch in C#

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#373]
This is an open issue for binary search algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by pranavkhapra** [comment]
Hey I can do the binary search problem with the correct explanation(i can try for that though)

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by Mayankjha997** [comment]
Please assign me this I will do it in c++ language

**Comment by Danushka96** [comment]
Hi @NidhiNivedita6 and @Mayankjha997 
Feel free to open new issues and start working on the implementation,

**Comment by Adithiyan** [comment]
Please assign me this. I will do it in java

**Comment by mertbarutcuoglu** [comment]
I can do it in GoLang! Please assign me.

**Comment by RavinduSachintha** [comment]
Hi @Adithiyan  and @mertbarutcuoglu 
Feel free to open **new issues** and start working on the implementation,

**Comment by anubhav2005** [comment]
I would like to work on this issue. I will use C# to solve this issue. can you please assign me with this issue? Thank you.

**Comment by Danushka96** [comment]
Hi @anubhav2005 
Start the implementation, the issue is yours!
Please read the [CONTRIBUTING.md](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) carefully.

**Comment by Danushka96** [comment]
Hi @anubhav2005 
Are you working on this?

**Comment by riturajjain2000** [comment]
can I work on it ?

**Comment by Danushka96** [comment]
Sure @riturajjain2000
