### ISSUE TITLE
BinarySearch in JavaScript

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#374]
This is an open issue for binary search algorithm implementation in JavaScript. If you wish to contribute, just make some noise and we will assign you.

**Comment by Srinjoycode** [comment]
Dear Sir, could you please assign me this issue.

**Comment by RavinduSachintha** [comment]
Good luck! :slightly_smiling_face: :+1:

**Comment by Srinjoycode** [comment]
Thank you !
