### ISSUE TITLE
BinarySearch in Python2

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#377]
This is an open issue for binary search algorithm implementation in Python2. If you wish to contribute, just make some noise and we will assign you.

**Comment by avsd47** [comment]
@RavinduSachintha please assign this to me

**Comment by RavinduSachintha** [comment]
Read the contribution file and make sure to use right file naming convention.
Good luck :+1:

**Comment by avsd47** [comment]
I sent the PR could  you please check it out

**Comment by avsd47** [comment]
I sent the PR could you please review it

**Comment by avsd47** [comment]
I edited and sent the pr again could ypu please review it

**Comment by RavinduSachintha** [comment]
> I edited and sent the pr again could ypu please review it

I will, but you have created 2 pull requests. As our guidance, you should keep a one PR for an issue. Can you close the unwanted pull request. Then I will review.

**Comment by avsd47** [comment]
I have deleted the other one
could you please review it again as far as i know pyhton 2 doesn't have braces in print statement but codacy os shpwing errpr i couldnt understand whats gng on....

**Comment by RavinduSachintha** [comment]
> I have closed the other one
> could you please review it again as far as i know pyhton 2 doesn't have braces in print statement but codacy os shpwing errpr i couldnt understand whats gng on....

I will review and tell you what you have to change. most of the issues are very simple things. after you fix them we will be able to merge the PR.
