### ISSUE TITLE
Binary Search in Golang

### ISSUE THREAD

**Issue by mertbarutcuoglu** [FOSS-UCSC/FOSSALGO#388]
This issue is about Binary Search in Golang.

**Comment by RavinduSachintha** [comment]
**Location:** [algorithms/ar-bsrh/golang](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-bsrh/golang)

- Make sure to use the right filename convention. (For golang - valid only simple letters & underscore)

Good luck ! :+1:

**Comment by mertbarutcuoglu** [comment]
@RavinduSachintha Hi! When I checked the implemented algorithms part this one seemed to be not implemented. However, there is an implementation in the directory. Should I change that one or is the current implementation missing from the table in the README.md ?

**Comment by RavinduSachintha** [comment]
If the current implementation is not proper, it would be better to change the existing one.

**Comment by mertbarutcuoglu** [comment]
I am closing this issue since there is an implementation for this.
