### ISSUE TITLE
Merge Sort in Golang

### ISSUE THREAD

**Issue by mertbarutcuoglu** [FOSS-UCSC/FOSSALGO#389]
This issue is about Merge Sort in Golang.

**Comment by kamil200** [comment]
i would like to contribute in this issue please assign me

**Comment by Danushka96** [comment]
Hi @kamil200 
Try another algorithm with checking if it's already implemented from the Readme file,
Cheers,

**Comment by Danushka96** [comment]
Hi @mertbarutcuoglu 
Are you working on this?

**Comment by mertbarutcuoglu** [comment]
Hi @Danushka96 

Yes, it is almost done. I am planning to push it by this Saturday.

**Comment by mertbarutcuoglu** [comment]
Hi @Danushka96 Can I close this issue if my pull request is okay? I want to implement some other algorithms but I have to close this one first.
