### ISSUE TITLE
BubbleSort in C++

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#397]
**Location:** [algorithms/ar-bsrt/cpp](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-bsrt/cpp)

- make sure to use only "simple letters" and "underscore" for the file name.

**Comment by AntoineDoniel** [comment]
can I be assigned this issue?

**Comment by RavinduSachintha** [comment]
> can I be assigned this issue?

We have already assigned someone else on this issue. You can make a new issue on any of the remaining algorithms or data-structures.
