### ISSUE TITLE
BubbleSort in JavaScript

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#399]
**Location:** [algorithms/ar-bsrt/javascript](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-bsrt/javascript)

- make sure to use only "simple letters" and "underscore" for the file name.
- don't use `console.log()`. it will produce errors in code reviews. Just implement the function and call it for some test cases.

**Comment by SravanthiKaki** [comment]
Can you assign this to me?

**Comment by RavinduSachintha** [comment]
> Can you assign this to me?

We have already assigned someone else on this issue. You can make a new issue on any of the remaining algorithms or data-structures.
Thank you.
