### ISSUE TITLE
BubbleSort in Python3

### ISSUE THREAD

**Issue by Aaditya1978** [FOSS-UCSC/FOSSALGO#404]
This is the issue about implementation of algorithm of bubble sort in python 3

**Comment by Aaditya1978** [comment]
@RavinduSachintha  Please Assign this issue to me

**Comment by RavinduSachintha** [comment]
**Location:** [algorithms/ar-bsrt/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-bsrt/python3)
@Aaditya1978 there already is an implementation for the bubble sort in python3. however, we are encouraging you to implement an improved bubble sort algorithm.
-  make sure to add a new file named using simple letters & underscore only.

Good luck :slightly_smiling_face: 
A quick reminder to star this repository. :wink:
