### ISSUE TITLE
Insertion sort in python 3

### ISSUE THREAD

**Issue by abhaydhiman** [FOSS-UCSC/FOSSALGO#405]
This is the issue about the implementation of the algorithm of `Insertion sort` in python 3

**Comment by abhaydhiman** [comment]
@RavinduSachintha Please assign the task for this issue to me.

**Comment by RavinduSachintha** [comment]
> This is the issue about the implementation of the algorithm of `Insertion sort` in python 3

The insertion sort in python3 is already implemented. Would you be able to do it for python2?

**Comment by abhaydhiman** [comment]
well, I did not comfortable in python2. So I'll just look at some other problem or enhancement in python3 itself.
Thank you!!
