### ISSUE TITLE
PrimeFactor in Python3

### ISSUE THREAD

**Issue by abhaydhiman** [FOSS-UCSC/FOSSALGO#415]
For this particular issue, I want to add a python program for finding the prime factors for any particular number.

**Comment by abhaydhiman** [comment]
@sachinthaR what you say about this issue? Can I add this?

**Comment by RavinduSachintha** [comment]
@abhaydhiman sorry for the late reply. If you still wish to contribute to this algorithm we can assign you for that.

**Comment by Danushka96** [comment]
Closed due to inactivity
