### ISSUE TITLE
Counting Sort Algorithm in Python 3

### ISSUE THREAD

**Issue by Ayush-Malik** [FOSS-UCSC/FOSSALGO#416]
I want to add the implementation of Counting Sort in python 3
@sachinthaR Please assign it to me

**Comment by RavinduSachintha** [comment]
@Ayush-Malik sorry for the late reply. Currently, the requested algorithm is not listed. but there are lots of other open issues. please select one from them. Thank you.

**Comment by RavinduSachintha** [comment]
we will close this issue due to the inactivity.
