### ISSUE TITLE
stack data structure implementation in CPP

### ISSUE THREAD

**Issue by akshita-sharma8609** [FOSS-UCSC/FOSSALGO#418]
#### This issue is about [Stack]

-   [x] Issue Title is in form `[Stack] in [CPP]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
@akshita-sharma8609 Good luck. make sure to read the guidelines and use the correct file naming conventions. our automated review system will show you if there is an issue in your PR when it creates. You need to make your PR to pass all the checks. :+1: 
And also support us by staring this repo and spreading the word about us. :wink:
