### ISSUE TITLE
Quick Sort Algorithm in C

### ISSUE THREAD

**Issue by Aaditya1978** [FOSS-UCSC/FOSSALGO#419]
#### This issue is about Quick Sort in C

-   [x] Issue Title is in form `[Quick Sort] in [C]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by Aaditya1978** [comment]
@RavinduSachintha Please assign this issue to me.

**Comment by RavinduSachintha** [comment]
I will assign you as soon as possible. Due to some code review system matter, I have to do some configuration for this algorithm. Please, be patient.

**Comment by Aaditya1978** [comment]
Ok Sure.

**Comment by RavinduSachintha** [comment]
**location:** [https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-qsrt](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-qsrt)
Now you can work on this issue. Good luck ! :+1:
