### ISSUE TITLE
Singly Linked List in Java

### ISSUE THREAD

**Issue by mertbarutcuoglu** [FOSS-UCSC/FOSSALGO#420]
#### This issue is about Linked List in Java

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

- [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
**location:** https://github.com/FOSS-UCSC/FOSSALGO/tree/master/data-structures/ds-slinklst/java
Good luck !
