### ISSUE TITLE
Bin-Sort in Java

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#429]
This is an open issue for bin sorting algorithm implementation in Java. If you wish to contribute, just make some noise and we will assign you.

**Comment by mertbarutcuoglu** [comment]
I can take this one!

**Comment by SravanthiKaki** [comment]
Can you assign this to me?

**Comment by Danushka96** [comment]
Hi @SravanthiKaki 
location: [https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-binsrt/java](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-binsrt/java)
Good luck !
