### ISSUE TITLE
Bin-Sort in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#430]
This is an open issue for bin sorting algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by Amulya-coder** [comment]
@Danushka96  Can I contribute to this. Please Assign it to me.

**Comment by RavinduSachintha** [comment]
@Amulya-coder good luck. Read the contribution guidelines first. :smile: 
**Location:** [/algorithms/ar-binsrt/c](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-binsrt/c)
