### ISSUE TITLE
Bin-Sort in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#431]
This is an open issue for bin sorting algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by vikumkbv** [comment]
@Danushka96 I'll do this

**Comment by Danushka96** [comment]
@vikumkbv Official Bin-Sorter of the FOSSALGO 🤣

**Comment by vikumkbv** [comment]
🤣
