### ISSUE TITLE
Bin-Sort in javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#435]
This is an open issue for bin sorting algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by vale-c** [comment]
Hi! Can I please work on this? :)

**Comment by vale-c** [comment]
Hi! Can I please work on this? :)

**Comment by Danushka96** [comment]
Hi @vale-c 
location: [https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-binsrt/javascript](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-binsrt/javascript)
Good luck !
