### ISSUE TITLE
Insertion Sort in Java

### ISSUE THREAD

**Issue by mertbarutcuoglu** [FOSS-UCSC/FOSSALGO#438]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS)

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x]  will send my PR only after I'm assigned to this issue by any maintainer

**Comment by Danushka96** [comment]
Hi @mertbarutcuoglu 
Insertion Sort in java is already implemented, But the Readme file is not up to date, You can update the Readme file.

**Comment by mertbarutcuoglu** [comment]
Hi @Danushka96 will do!
