### ISSUE TITLE
Simple documentation for binary search algorithm

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#443]
# [Title] 
[short description - you can make links to any proper, publicly available explanations of the algorithm.]

# Implementations
[add links to currently available implementation under the corresponding folder according to the languages]

**Comment by amohapatra123** [comment]
i want to work on this ,can you assign it to me.

**Comment by zinthanmm** [comment]
I would like to contribute to this. @RavinduSachintha

**Comment by Danushka96** [comment]
Hi @zinthanmm 
Good Luck, I assigned the issue
