### ISSUE TITLE
Simple documentation for bubble sort algorithm

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#444]
# [Title] 
[short description - you can make links to any proper, publicly available explanations of the algorithm.]

# Implementations
[add links to currently available implementation under the corresponding folder according to the languages]

**Comment by zinthanmm** [comment]
I would like to contribute to this. @RavinduSachintha

**Comment by Danushka96** [comment]
Hi @zinthanmm 
Good Luck, I assigned the issue

**Comment by zinthanmm** [comment]
Just for clarification, updating the relevant readme file with links (publicly available explanations of the algorithm) related to each language is what needed right? @Danushka96

**Comment by RavinduSachintha** [comment]
@zinthanmm for the first section (title) add an introduction or simple explanation for the algorithm. you can add some links for more information/explanations, images, animated gifs, etc if you want. The second section (implementations) should contain a list of language which is linked to the relevant algorithm file. for example, 

# Bubble Sort Algorithm

Introduction/explanation

# Implementations

[Java](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/algorithms/ar-bsrt/java/BubbleSort.java)

----
If you expect to add images or any other assets on the readme make sure to publish them publicly & free on somewhere or you can add it to the issue and then get the link for github published contents. :wink:
