### ISSUE TITLE
Breadth First Search in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#455]
This is an open issue for the Breadth-First Search algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by vale-c** [comment]
Hello! Can I please work on this issue? :) Thanks!

**Comment by Amulya-coder** [comment]
@Danushka96 If he is not working on it can I contribute to this . Kindly Assign it to me . Thanks

**Comment by Danushka96** [comment]
Hi @vale-c 
What's your status?

**Comment by vale-c** [comment]
Hi @Danushka96 ! I'm still working on it and it should be ready soon but if I don't open a PR by the end of the day you can feel free to assign it to somebody else if you wish.

**Comment by Danushka96** [comment]
@vale-c Great! Thanks,
