### ISSUE TITLE
Breadth First Search in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#456]
This is an open issue for the Breadth-First Search algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by Harshalszz** [comment]
Hey! can I work on this.

**Comment by Danushka96** [comment]
Hi @Harshalszz 
Sure, location: [https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/gr-bfsrh/cpp](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/gr-bfsrh/cpp)
Please read the [contribution ](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md)guide for fewer changes.
