### ISSUE TITLE
Breadth First Search in python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#459]
This is an open issue for the Breadth-First Search algorithm implementation in python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by TokyoDom** [comment]
Hi, I'd like to tackle this issue!

**Comment by Danushka96** [comment]
Hi @TokyoDom 
Great! Code location should be [https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/gr-bfsrh/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/gr-bfsrh/python3)
Please read the [contribution ](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) guide for fewer troubles.
