### ISSUE TITLE
Breadth First Search in javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#461]
This is an open issue for the Breadth-First Search algorithm implementation in javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by vale-c** [comment]
Hi @Danushka96 ! Can I please be assigned to this issue? I'd really like to work on it. Thank you!

**Comment by vale-c** [comment]
Hi! You can feel free to assign this issue to somebody else. :)

**Comment by RavinduSachintha** [comment]
> Hi! You can feel free to assign this issue to somebody else. :)

okay :+1: thank you for your contribution. 😊

**Comment by LaxmiNyamagoud** [comment]
can I work on this issue? please assign me
