### ISSUE TITLE
Breadth First Search in Typescript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#462]
This is an open issue for the Breadth-First Search algorithm implementation in TypeScript. If you wish to contribute, just make some noise and we will assign you.

**Comment by SahanAmarsha** [comment]
@Danushka96 I can work on this.

**Comment by Danushka96** [comment]
@SahanAmarsha  Great! Please read the contribution guideline carefully. Thanks!

**Comment by SahanAmarsha** [comment]
Noted:+1:. I'll start right away.
