### ISSUE TITLE
shell sort in python3

### ISSUE THREAD

**Issue by charindukavishan** [FOSS-UCSC/FOSSALGO#481]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS)

-   [ ] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [ ] Assign this issue to me (I want to work on this)

   -   [ ] I ensure that I am not already assigned to 2 or more issues
  
-   [ ] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
@charindukavishan Good luck bro :smile: 
Take a look at the contributing doc first.
**Location:** [/algorithms/ar-shsrt/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-shsrt/python3)
