### ISSUE TITLE
Bubble Sort in Typescript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#486]
This is an open issue for the Bubble Sort algorithm implementation in Typescript. If you wish to contribute, just make some noise and we will assign you.

**Comment by Wei-J-Huang** [comment]
I would like to work on this please  :)

**Comment by Danushka96** [comment]
@Wei-J-Huang 
Great! Please read the contribution guideline before the implementation. 
Thanks
