### ISSUE TITLE
Depth First Search in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#487]
This is an open issue for the Depth First Search algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by KoushikSahu** [comment]
I want to work on this issue. Please assign it to me.

**Comment by RavinduSachintha** [comment]
@KoushikSahu good luck :+1: make sure to read the contributing doc first.

**Comment by KoushikSahu** [comment]
@RavinduSachintha I have made a PR. Please review it.
