### ISSUE TITLE
Depth First Search in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#488]
This is an open issue for the Depth First Search algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by riturajjain2000** [comment]
Can I work on it ?

**Comment by RavinduSachintha** [comment]
> Can I work on it ?

good luck @riturajjain2000 :+1:  make sure to read the contributing doc first.

**Comment by riturajjain2000** [comment]
> > Can I work on it ?
> 
> good luck @riturajjain2000 👍 make sure to read the contributing doc first.

sure sir :)
