### ISSUE TITLE
Depth First Search in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#489]
This is an open issue for the Depth First Search algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by jcasteele** [comment]
I'd be interested in doing the C# DFS

**Comment by Danushka96** [comment]
Hi @jcasteele 
I will assign the issue, please read the contribution guidelines first!

**Comment by aditisneh** [comment]
> This is an open issue for the Depth First Search algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

i wanted to work on the issue, please assign me:)

**Comment by RavinduSachintha** [comment]
> > This is an open issue for the Depth First Search algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.
> 
> i wanted to work on the issue, please assign me:)

first come first serve :smile: there are lots of open issues. you can work on one of them @aditisneh

**Comment by Danushka96** [comment]
Hi @jcasteele 
How's your progress?

**Comment by jcasteele** [comment]
Working on finishing it up now, actually. Will test and hopefully have it ready later today
________________________________

**Comment by Danushka96** [comment]
Hi @jcasteele 
Are you still working on this?

**Comment by jcasteele** [comment]
Apologies, ran into an issue that needed to be fixed and have since been hit with some issues in Real Life that have kept me away from the computer. Feel free to open this back up or assign it to someone else if you wish as it might be a little bit before I have time to work on it again
