### ISSUE TITLE
Depth First Search in Java

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#490]
This is an open issue for the Depth First Search algorithm implementation in Java. If you wish to contribute, just make some noise and we will assign you.

**Comment by erikrios** [comment]
Hey @Danushka96, can i work on this

**Comment by RavinduSachintha** [comment]
@erikrios good luck! make sure to read the contributing doc first.

**Comment by pnqphong** [comment]
Hi @RavinduSachintha , @Danushka96 CC: @erikrios 
I don't know if I can start this issue again?

**Comment by Danushka96** [comment]
@pnqphong 
you can work on this,
