### ISSUE TITLE
Depth First Search in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#494]
This is an open issue for the Depth First Search algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by pnqphong** [comment]
Hi @Danushka96, Could i work on this?

**Comment by Danushka96** [comment]
@pnqphong  Sure! make sure to read the contributing doc first.

**Comment by Danushka96** [comment]
Hi @pnqphong 
Are you working on this?

**Comment by pnqphong** [comment]
HI @Danushka96 , yes. I still work on it. Implementation is done. will PR soon.

**Comment by Danushka96** [comment]
Great!
