### ISSUE TITLE
Depth First Search in Typescript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#495]
This is an open issue for the Depth First Search algorithm implementation in Typescript. If you wish to contribute, just make some noise and we will assign you.

**Comment by FaMoSi** [comment]
I would like to work on this :)

**Comment by Danushka96** [comment]
@charindukavishan Good luck bro 😄
Take a look at the contributing doc first.
Location: [/algorithms/ar-shsrt/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-shsrt/python3)

**Comment by FaMoSi** [comment]
Are you sure te location is [/algorithms/ar-shsrt/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-shsrt/python3) and not [/algorithms/ar-shsrt/typescript](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-shsrt/typescript)?

**Comment by RavinduSachintha** [comment]
> Are you sure te location is [/algorithms/ar-shsrt/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-shsrt/python3) and not [/algorithms/ar-shsrt/typescript](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-shsrt/typescript)?

:smile: You are right. He has mistaken.

**Comment by Danushka96** [comment]
@FaMoSi 
Sorry, my mistake, 🤐
