### ISSUE TITLE
Prime Factor in Java

### ISSUE THREAD

**Issue by JayeshJanyani** [FOSS-UCSC/FOSSALGO#505]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS)

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

This is an open issue for the Prime factor algorithm implementation in Java. I want to contribute, Please assign it to me.

**Comment by JayeshJanyani** [comment]
Please assign this issue to me.

**Comment by Danushka96** [comment]
@JayeshJanyani Good luck! Make sure to read the contributing doc first.
