### ISSUE TITLE
Dijkstra Algorithm in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#529]
This is an open issue for the Dijkstra Algorithm algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by ravidyarev** [comment]
@Danushka96 Please assign this to me

**Comment by riturajjain2000** [comment]
Can I work on it?

**Comment by Danushka96** [comment]
@riturajjain2000 sure!
