### ISSUE TITLE
Dijkstra Algorithm in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#531]
This is an open issue for the Dijkstra Algorithm algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by shouvikch97** [comment]
I want to help. Will you please assign this to me?

**Comment by Danushka96** [comment]
@shouvikch97 Sure! Please read the contribution guidelines first! Good luck!
