### ISSUE TITLE
Dijkstra Algorithm in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#534]
This is an open issue for the Dijkstra Algorithm algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by LaxmiNyamagoud** [comment]
can I work on this issue?

**Comment by Danushka96** [comment]
Hi @LaxmiNyamagoud 
Sure, please read the contribution guidelines first! Good luck!

**Comment by LaxmiNyamagoud** [comment]
ok 
thanks!

**Comment by Danushka96** [comment]
Hi @LaxmiNyamagoud 
Are you working on this?

**Comment by LaxmiNyamagoud** [comment]
> Hi @LaxmiNyamagoud
> Are you working on this?

yes

**Comment by Danushka96** [comment]
Great! Thanks

**Comment by LaxmiNyamagoud** [comment]
please check my PR and confirm
