### ISSUE TITLE
Dijkstra Algorithm in Golang

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#535]
This is an open issue for the Dijkstra Algorithm algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

**Comment by android-lewis** [comment]
Hey man, wonder if you could assign this to me so I can have a go?

**Comment by Danushka96** [comment]
@android-lewis Sure, Please read the contribution guidelines first! Good Luck!
