### ISSUE TITLE
Dijkstra Algorithm in Python2

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#537]
This is an open issue for the Dijkstra Algorithm algorithm implementation in Python2. If you wish to contribute, just make some noise and we will assign you.

**Comment by janethavi** [comment]
Can I get assigned for this issue?

**Comment by MrLukeKR** [comment]
Hi there, could I be assigned to this?

**Comment by RavinduSachintha** [comment]
> Hi there, could I be assigned to this?

One issue at a time :smile:

**Comment by RavinduSachintha** [comment]
@MrLukeKR now you can :smile:
