### ISSUE TITLE
Prime factors in C

### ISSUE THREAD

**Issue by EANimesha** [FOSS-UCSC/FOSSALGO#538]
####This is an open issue for the Prime Factors algorithm implementation in C.

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
@EANimesha as our guidelines you will have to create a single issue for a single case (algorithm/data-structure). And each PR should be linked to a single issue. You can change this issue appropriately. Then we will assign you for that. And make sure to read the contributing doc first. :+1:

**Comment by RavinduSachintha** [comment]
Good luck :+1:
