### ISSUE TITLE
Prime Factors in Python 3

### ISSUE THREAD

**Issue by iamyajat** [FOSS-UCSC/FOSSALGO#545]
### This issue is about Prime Factors algorithm implementation in Python 3

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
@iamyajat good luck! read the contributing doc first.
