### ISSUE TITLE
Insertion Sort in JavaScript

### ISSUE THREAD

**Issue by EANimesha** [FOSS-UCSC/FOSSALGO#550]
#### This is an open issue for the Insertion Sort algorithm implementation in JavaScript.

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by Danushka96** [comment]
Hi @EANimesha 
Good luck and read the contribution guidelines, Thanks!
