### ISSUE TITLE
Merge sort in Typescript

### ISSUE THREAD

**Issue by Any0ne22** [FOSS-UCSC/FOSSALGO#552]
#### This issue is about merge sort in Typescript

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
> #### This issue is about merge sort in Typescript
> * [x]  I ensure that I am not already assigned to 2 or more issues

If I assign you to this one, above your statement will be false. 😅 
So let's put this issue as an open one. If you complete the other issue that you have already assigned, we will assign you to this one also.

**Comment by Any0ne22** [comment]
Okay my bad, I thought that I could be assigned to two issues but not more

**Comment by Any0ne22** [comment]
Can I be assigned to this issue ?
