### ISSUE TITLE
Circular Queue in C

### ISSUE THREAD

**Issue by EANimesha** [FOSS-UCSC/FOSSALGO#559]
#### This issue is about Cricular Queue data Structure In C

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
good luck :+1:
