### ISSUE TITLE
Circular Queue in Java

### ISSUE THREAD

**Issue by EANimesha** [FOSS-UCSC/FOSSALGO#560]
#### This issue is about Circular Queue in data Structures with Java

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by Danushka96** [comment]
Hi @EANimesha 
We can't assign you to this issue since you are already working on issue #559

**Comment by Danushka96** [comment]
Hi @EANimesha 
are you working on this?

**Comment by EANimesha** [comment]
> Hi @EANimesha
> are you working on this?

Yeah. I will send PR today
