### ISSUE TITLE
Coin Change Problem in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#566]
This is an open issue for the Coin Change Problem algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by Symbolism00** [comment]
i can work on that mate!

**Comment by RavinduSachintha** [comment]
@Symbolism00 good luck!! Make sure to read the contributing doc first.

**Comment by Danushka96** [comment]
Hi @Symbolism00 
Are you working on this?

**Comment by Symbolism00** [comment]
Hey @Danushka96 
I already finished this issue and did everything that you wanted me to do

**Comment by RavinduSachintha** [comment]
> Hey @Danushka96
> I already finished this issue and did everything that you wanted me to do

sorry. there has happened some mistake in the issue linking to the PR. :smile:
