### ISSUE TITLE
Coin Change Problem in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#567]
This is an open issue for the Coin Change Problem algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by divyanshkhatana** [comment]
@Danushka96  please assign this to me .i will do this in c++

**Comment by poojitha2002** [comment]
@Danushka96 sir please assign it to me, I will do coin change problem in c++.

**Comment by Danushka96** [comment]
@divyanshkhatana Great! Read the contribution guidelines first! Good Luck!

**Comment by Danushka96** [comment]
@poojitha2002 
Issues are assigned on a First Come First Serve basis. There are a bunch of issues out there, take a look. Thanks!

**Comment by Danushka96** [comment]
Hi @divyanshkhatana 
Are you working on this?

**Comment by divyanshkhatana** [comment]
I have already added 
--
Sent from myMail for Android Sunday, 18 October 2020, 09:55pm +05:30 from Danushka Herath  notifications@github.com :

**Comment by Danushka96** [comment]
Can you send a link to your PR, please?
