### ISSUE TITLE
Coin Change Problem in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#568]
This is an open issue for the Coin Change Problem algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by Infinityz** [comment]
Could I work on this?

**Comment by Danushka96** [comment]
@Infinityz Sure, Please read the contribution guidelines first! Good luck!

**Comment by Danushka96** [comment]
Hi @Infinityz 
Are you working on this?

**Comment by MarkMuth** [comment]
Sounds interesting. Would you assign me?

**Comment by MarkMuth** [comment]
So what is your definition of the coin change problem? I just tried out the C and the JAVA versions and they yield different result for the same inputs. For example having the coins {6,2,3} and a target sum of 8, we get 3 combinations in C, but 6 number of ways in JAVA.

**Comment by MarkMuth** [comment]
I implemented this now based on the definition on Wikipedia. It's consistent with the C and also with the Python 3 version.

**Comment by Danushka96** [comment]
That would be good,
