### ISSUE TITLE
Coin Change Problem in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#571]
This is an open issue for the Coin Change Problem algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by I3han** [comment]
Hello, I would Like to contribute

**Comment by RavinduSachintha** [comment]
Good luck! read the contribution guideline first.

**Comment by I3han** [comment]
@RavinduSachintha can you check my PR thank you

**Comment by I3han** [comment]
Sorry for the mistake @RavinduSachintha

**Comment by RavinduSachintha** [comment]
> Sorry for the mistake @RavinduSachintha

don't worry. :smiley: we should make mistakes and we should learn from them. :+1:
