### ISSUE TITLE
Coin Change Problem in Golang

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#572]
This is an open issue for the Coin Change Problem algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

**Comment by sg-4** [comment]
I would like to contribute.

**Comment by Danushka96** [comment]
Hi @sg-4 Good Luck!

**Comment by sg-4** [comment]
I unassigned by mistake.
