### ISSUE TITLE
Coin Change Problem in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#573]
This is an open issue for the Coin Change Problem algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by sg-4** [comment]
hi. I would like to contribute.

**Comment by Danushka96** [comment]
Great! @sg-4 please read the contribution guidelines first! Good Luck!

**Comment by sg-4** [comment]
Thank you for your email
