### ISSUE TITLE
Exponentiation by Squaring in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#597]
This is an open issue for the Exponentiation by Squaring algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by KingSlayr** [comment]
please assign this to me .i will do this in c++

**Comment by Danushka96** [comment]
Sure! @KingSlayr Please read the contribution guidelines first! Good luck!

**Comment by KingSlayr** [comment]
thanks!

**Comment by Danushka96** [comment]
@KingSlayr 
Let me know if you still wish to continues
