### ISSUE TITLE
Exponentiation by Squaring in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#598]
This is an open issue for the Exponentiation by Squaring algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by devblin** [comment]
Hey, I would love to contribute :). Can you assign this to me?

**Comment by devblin** [comment]
Hey, can I work on this issue ?

**Comment by devblin** [comment]
Hey, can you assign this to me?
