### ISSUE TITLE
Exponentiation by Squaring in Java

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#599]
This is an open issue for the Exponentiation by Squaring algorithm implementation in Java. If you wish to contribute, just make some noise and we will assign you.

**Comment by KingSlayr** [comment]
please assign this to me .i will do this in c++

**Comment by Danushka96** [comment]
@KingSlayr You can only be assigned to a single issue!

**Comment by KingSlayr** [comment]
Im most proficient in c++
Please assign the c++ implementation

**Comment by Infinityz** [comment]
Could I work on this?

**Comment by rishier827** [comment]
can i get assigned

**Comment by Danushka96** [comment]
Hi @rishier827 
Waiting for the changes in #622

**Comment by rishier827** [comment]
i finished the changes in #622  so can i get assigned for this

**Comment by Danushka96** [comment]
Hi @rishier827 
Sure,
