### ISSUE TITLE
Exponentiation by Squaring in Golang

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#601]
This is an open issue for the Exponentiation by Squaring algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

**Comment by ankit-rawani** [comment]
Heyy, Assign this to me please!

**Comment by Danushka96** [comment]
Hi @ankit-rawani 
you are already working on #603 let's finish it first

**Comment by ankit-rawani** [comment]
I have already the pr for that one, just review it to merge

**Comment by RavinduSachintha** [comment]
> I have already sent the pr for that one, just review it to merge

the reviewing is happening via an automated system. sometimes due to the heavy traffic, it will take some time. after that PR is merged, let's work on this. Thank you.

**Comment by BLasan** [comment]
@Danushka96 Can I work on this?

**Comment by Danushka96** [comment]
Hi @BLasan 
Please read the contribution guidelines first and good luck!
