### ISSUE TITLE
Exponentiation by Squaring in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#602]
This is an open issue for the Exponentiation by Squaring algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by MrLukeKR** [comment]
Hi there, could I be assigned to this?

**Comment by RavinduSachintha** [comment]
@MrLukeKR good luck! make sure to read the contribution guidelines first.
