### ISSUE TITLE
Exponentiation by Squaring in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#603]
This is an open issue for the Exponentiation by Squaring algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by KingSlayr** [comment]
please assign this to me .i will do this in c++

**Comment by Danushka96** [comment]
@KingSlayr You can only be assigned to a single issue!

**Comment by ankit-rawani** [comment]
Hey Can you assign this to me?

**Comment by Danushka96** [comment]
@ankit-rawani 
Sure! Please read the contribution guidelines first! 
Thanks

**Comment by Danushka96** [comment]
Hi @ankit-rawani 
You have already assigned to #628

**Comment by ankit-rawani** [comment]
Can you assign this one to me?

**Comment by ankit-rawani** [comment]
And remove the earlier one?

**Comment by ankit-rawani** [comment]
Please

**Comment by ankit-rawani** [comment]
Assign this one to me now! I have been unassigned from the earlier one

**Comment by ankit-rawani** [comment]
Thank you
And sorry for the inconvenience

**Comment by RavinduSachintha** [comment]
Good luck! Please read the contributing doc first

**Comment by ankit-rawani** [comment]
PR sent, please review
