### ISSUE TITLE
Exponentiation by Squaring in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#605]
This is an open issue for the Exponentiation by Squaring algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by devblin** [comment]
Hey, I would love to contribute.

**Comment by RavinduSachintha** [comment]
@devblin as our contribution guidelines, you are allowed to assign for a single issue per once. To which issue you need to be assigned?

**Comment by devblin** [comment]
I would work on this issue.

**Comment by RavinduSachintha** [comment]
> I would work on this issue.

good luck! read the contribution doc first. :+1:
