### ISSUE TITLE
Bin Sort in Python2

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#623]
This is an open issue for the Bin Sort algorithm implementation in Python2. If you wish to contribute, just make some noise and we will assign you.

**Comment by shinigami2905** [comment]
I would like to work on this issue 😃

**Comment by RavinduSachintha** [comment]
> I would like to work on this issue

let's first finish #624 :wink:

**Comment by shinigami2905** [comment]
> 
> 
> > I would like to work on this issue
> 
> let's first finish #624 😉

Thanks for assigning me for that issue!! Would like to assign me here too? 😅

**Comment by RavinduSachintha** [comment]
> Thanks for assigning me for that issue!! Would like to assign me here too?

😄 now you can work on this. good luck :+1:
