### ISSUE TITLE
Heap Sort in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#624]
This is an open issue for the Heap Sort algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by Jeewantha95** [comment]
Can I contribute?

**Comment by RavinduSachintha** [comment]
> Can I contribute?

one issue at a time

**Comment by shinigami2905** [comment]
I would like to work on this issue 😃

**Comment by RavinduSachintha** [comment]
@shinigami2905 good luck! please read the contribution doc before starting the implementation.

**Comment by shinigami2905** [comment]
I will complete it asap! Thanks!
