### ISSUE TITLE
Heap Sort in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#625]
This is an open issue for the Heap Sort algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by Jeewantha95** [comment]
Can i contribute?

**Comment by RavinduSachintha** [comment]
> Can i contribute?

you will have to complete the already assigned issue before assign to this.

**Comment by MarkMuth** [comment]
Hi, I'd like to be assigned to this issue. And also suggest F# as an additional language.

**Comment by RavinduSachintha** [comment]
@MarkMuth good luck! Please read the contributing doc first.
