### ISSUE TITLE
Heap Sort in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#627]
This is an open issue for the Heap Sort algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by liamm91** [comment]
Can I contribute?

**Comment by Danushka96** [comment]
Hi @liamm91 
you are already assigned to #632

**Comment by hasalfernando** [comment]
Hi, since this isn't unassigned, I would like to be assigned to this.

**Comment by RavinduSachintha** [comment]
@hasalfernando good luck! please read the contribution guidelines first.
