### ISSUE TITLE
Heap Sort in Golang

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#628]
This is an open issue for the Heap Sort algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

**Comment by ankit-rawani** [comment]
Hey!! Can I try this one?

**Comment by Danushka96** [comment]
Hi @ankit-rawani 
Please read the contribution guidelines first! Good luck!

**Comment by ankit-rawani** [comment]
Thanks

**Comment by ankit-rawani** [comment]
Heyy I can be assigned to only a single issue it seems
Can you please unassign me, since I already got assigned to another one?
