### ISSUE TITLE
Heap Sort in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#629]
This is an open issue for the Heap Sort algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by iccir919** [comment]
Here is some **noise**. Please assign this issue to me!

**Comment by Danushka96** [comment]
😅😅 Great! 
Please read the contribution guidelines first! Issue is yours

**Comment by Danushka96** [comment]
Hi @iccir919 
Let me know if you still wish to continue
