### ISSUE TITLE
Insertion Sort in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#632]
This is an open issue for the Insertion Sort algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by Jeewantha95** [comment]
Can I contribute?

**Comment by liamm91** [comment]
Can I contribute?

**Comment by Danushka96** [comment]
Sure @liamm91 Please read the contribution guidelines first! Thanks!
