### ISSUE TITLE
Insertion Sort in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#633]
This is an open issue for the Insertion Sort algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by Jeewantha95** [comment]
Can I contribute?

**Comment by Danushka96** [comment]
Hi @Jeewantha95 
Once #634 resolved, we can reassign you to this task
Thanks

**Comment by riturajjain2000** [comment]
Can I work on it ?
