### ISSUE TITLE
Insertion Sort in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#634]
This is an open issue for the Insertion Sort algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by Jeewantha95** [comment]
Can i Contribute?

**Comment by Danushka96** [comment]
@Jeewantha95 Sure, Read the contribution guidelines first, Good Luck!

**Comment by Danushka96** [comment]
Hi @Jeewantha95 
Are you working on this?
