### ISSUE TITLE
Brute Force/Naive Algorithm in C

### ISSUE THREAD

**Issue by AmithLiyanage** [FOSS-UCSC/FOSSALGO#7]
This issues is about "Brute Force/Naive Algorithm" in java.https://www.geeksforgeeks.org/searching-for-patterns-set-1-naive-pattern-searching/

- [x] Issue title form Algo/DS Name [Language]

- [x] I searched or browsed the repo's other issues to ensure this is not a duplicate

- [x] This Algo/DS is worth to add this repository

- [x] Assign this issue to me

- [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
After you finish your remaining and assigned issues, We will assign you for this.
