### ISSUE TITLE
K-NN in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#709]
This is an open issue for the K-NN algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by aayushbest** [comment]
I want to contribute to this algorithm.

**Comment by Danushka96** [comment]
Hi @aayushbest 
Are you working on this?

**Comment by aayushbest** [comment]
I already made the pull request and submitted it and you merged that too

**Comment by Danushka96** [comment]
Hi @aayushbest 
Sorry I didn't check if it's linked to the PR, 
Please make sure that you linked the issue with your PR!
Thanks for the contribution

**Comment by aayushbest** [comment]
Sure next time I will make sure to link the related issue.
