### ISSUE TITLE
Largest Sum Contiguous Sub-Array in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#724]
This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by Danushka96** [comment]
Hi @beertocode 
Read the contribution guidelines first! 
Thanks
