### ISSUE TITLE
Largest Sum Contiguous Sub-Array in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#725]
This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by ankitgauri26** [comment]
Please assign it to me

**Comment by Danushka96** [comment]
Hi @ankit-rawani 
Let me know if you still want to work on this issue,

**Comment by ankit-rawani** [comment]
Sorry, I'm a bit busy cuz of college acads these days. I don't think I would be able to do this now.

**Comment by ankit-rawani** [comment]
I hope you understand

**Comment by Danushka96** [comment]
Hi @ankit-rawani 
Its ok,
