### ISSUE TITLE
Largest Sum Contiguous Sub-Array in Golang

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#728]
This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

**Comment by bmpj13** [comment]
> This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

Can you assign me please? 🙏
