### ISSUE TITLE
Largest Sum Contiguous Sub-Array in C

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#730]
This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in C. If you wish to contribute, just make some noise and we will assign you.

**Comment by EmanuelTinoco** [comment]
Hi @Danushka96, can you assign this issue to me?

**Comment by Danushka96** [comment]
Hi @EmanuelTinoco 
Are you working on this?

**Comment by Danushka96** [comment]
Hi @EmanuelTinoco 
Let me know if you still want to work on this,
