### ISSUE TITLE
Largest Sum Contiguous Sub-Array in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#732]
This is an open issue for the Largest Sum Contiguous Sub-Array algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by LON3WO7F** [comment]
Hey @Danushka96 
Please assign this to me.

**Comment by Danushka96** [comment]
Hi @LON3WO7F 
Read the contribution guidelines first!
Thanks
