### ISSUE TITLE
Linear Regression in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#733]
This is an open issue for the Linear Regression algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by Danushka96** [comment]
Hi @beertocode 
You can only get assigned to a single issue!
Thanks

**Comment by aayushbest** [comment]
Hi @Danushka96 
I want to contribute to this issue.

**Comment by adhilcodes** [comment]
@Danushka96 I would like to contribute , please assign me on this issue

**Comment by Danushka96** [comment]
Hi @adhilcodes 
This issue is already assigned! There are a bunch of other issues you can contribute to or create your own one!

**Comment by aayushbest** [comment]
Hi @adhilcodes 
I already started working on it

**Comment by Danushka96** [comment]
@aayushbest 
Great!
