### ISSUE TITLE
Linear Regression in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#734]
This is an open issue for the Linear Regression algorithm implementation in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by adhilcodes** [comment]
@Danushka96 I would like to contribute , please assign me on this issue

**Comment by Danushka96** [comment]
Hi @adhilcodes 
Please read the contribution guidelines first!
Thanks

**Comment by Danushka96** [comment]
Hi @adhilcodes 
Are you working on this?
