### ISSUE TITLE
Linear Regression in Java

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#737]
This is an open issue for the Linear Regression algorithm implementation in Java. If you wish to contribute, just make some noise and we will assign you.

**Comment by elizabethqiu** [comment]
Could I try helping with this issue?

**Comment by Danushka96** [comment]
@elizabethqiu 
Sure, please read the contribution guidelines first! Thanks!

**Comment by Danushka96** [comment]
Hi @elizabethqiu 
Are you working on this?

**Comment by elizabethqiu** [comment]
Hi! I'm working on it. I have the idea, but I'm not 100% sure on how to implement it in code.
