### ISSUE TITLE
Linear Regression in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#741]
This is an open issue for the Linear Regression algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by rdr42** [comment]
@Danushka96 I can take this one! What are the requirements for the liner regression function?

**Comment by rdr42** [comment]
@Danushka96 I see it now! I looked at some examples in the repo! Will submit a PR soon.

**Comment by Danushka96** [comment]
Great @rdr42 
Please read the contribution guidelines first! 
Thanks
