### ISSUE TITLE
Linear Search in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#774]
This is an open issue for the Linear Search algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by harithamohan1** [comment]
Hey, I am interested in helping out with this issue!

**Comment by Danushka96** [comment]
Hi @harithamohan1 
Read the contribution guidelines first! Thanks

**Comment by GetsugaTenzo** [comment]
Hi. I would like to know about the problem.

**Comment by RavinduSachintha** [comment]
> Hi. I would like to know about the problem.

@GetsugaTenzo Linear search is a simple method for finding an element within a list. It sequentially checks each element of the list until a match is found or the whole list has been searched. You can check other language implementations for linear search from [this](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-lsrh) folder. If you wish to contribute, we can assign you for this.

**Comment by GetsugaTenzo** [comment]
Yes, I am willing to. But I am new to this contribution concept. So
will I be given the problem that I am supposed to debug/rectify or should I
go through the issues of repository mentioned in the email?

Kindly brief me.

As soon as I know fhe problem I have to work on, I will be on it.

Thank you

**Comment by GetsugaTenzo** [comment]
> > Hi. I would like to know about the problem.
> 
> @GetsugaTenzo Linear search is a simple method for finding an element within a list. It sequentially checks each element of the list until a match is found or the whole list has been searched. You can check other language implementations for linear search from [this](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-lsrh) folder. If you wish to contribute, we can assign you for this.



> > Hi. I would like to know about the problem.
> 
> @GetsugaTenzo Linear search is a simple method for finding an element within a list. It sequentially checks each element of the list until a match is found or the whole list has been searched. You can check other language implementations for linear search from [this](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-lsrh) folder. If you wish to contribute, we can assign you for this.

Hello. I got this. Linear search in python 3 should be contributed right? I am in. Please assign me. I am working on the code.

**Comment by GetsugaTenzo** [comment]
Hai. I completed the Linear Search code for #774 issue and is ready to be pulled. I have read in guidelines that I need to be assigned to give a pull request. Kindly Assign me.

Thank you.

**Comment by GetsugaTenzo** [comment]
Hai. I submitted a pull request. Please verify.

**Comment by GetsugaTenzo** [comment]
I rectified my trailing spaces.

**Comment by Danushka96** [comment]
Hi @GetsugaTenzo 
Sorry for the late reply,
Can you add your algorithm to the main algorithm table with a tick? 
Send the commit to this PR, 
Thanks
