### ISSUE TITLE
Linear Search in Golang

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#775]
This is an open issue for the Linear Search algorithm implementation in Golang. If you wish to contribute, just make some noise and we will assign you.

**Comment by vishal-wadhwa** [comment]
Hey, I'd like to work on this. Can you please assign this to me?

**Comment by Danushka96** [comment]
Hi @vishal-wadhwa 
Please read the contribution guidelines first! 
Thanks

**Comment by vishal-wadhwa** [comment]
Hey, thanks!
Please check https://github.com/FOSS-UCSC/FOSSALGO/pull/794
