### ISSUE TITLE
Linear Search in Javascript

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#776]
This is an open issue for the Linear Search algorithm implementation in Javascript. If you wish to contribute, just make some noise and we will assign you.

**Comment by LaxmiNyamagoud** [comment]
can I work on this issue? please assign me.

**Comment by Danushka96** [comment]
@LaxmiNyamagoud 
Sure

**Comment by LaxmiNyamagoud** [comment]
Thanks!
