### ISSUE TITLE
Longest Common Subsequence in Python3

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#785]
This is an open issue for the Longest Common Subsequence algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by gpk2000** [comment]
Hey, I can implement this algorithm, and I have read your contribution markdown file.

**Comment by RachanaKampli** [comment]
hey,can you assign this to me?

**Comment by Danushka96** [comment]
Hi @RachanaKampli 
Issues are assigned on a first come first serve basis,
You can search for other issues or feel free to create one if not exists,
Thanks
