### ISSUE TITLE
InsertionSort in C++

### ISSUE THREAD

**Issue by RavjotSandhu** [FOSS-UCSC/FOSSALGO#792]
#### This issue is about Insertion Sort(https://www.interviewbit.com/tutorial/insertion-sort-algorithm/)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

**Comment by Danushka96** [comment]
@RavjotSandhu 
Give me a one day, There a PR #704 need to review because it's about this issue,

**Comment by Danushka96** [comment]
#634 
Put a comment in here, I will assign, 
This one is already assigned, but seems inactive,
you can take it,

**Comment by RavjotSandhu** [comment]
ok. It is still unmerged right?(I saw conversation) Assign to me then

**Comment by Danushka96** [comment]
It will take one day to consider as it's inactive,

**Comment by RavjotSandhu** [comment]
Can I open another issue till then? I noticed Merge ,Quick Sorts are still not done and they neither in closed and open issues. Selection sort status is also same like Insertion sort. Tell which issue do i open first?

**Comment by Danushka96** [comment]
Yes feel free to open an issue if the issue is not created yet, If no one is assigned I can assign you for that,

**Comment by Danushka96** [comment]
Hi @RavjotSandhu 
You can work on this.
