### ISSUE TITLE
Breadth First Search In Java

### ISSUE THREAD

**Issue by pnqphong** [FOSS-UCSC/FOSSALGO#801]
#### This issue is about [Breadth First Search](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/gr-bfsrh/java)

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

-   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by pnqphong** [comment]
@Danushka96 I opened this issue to update BFS in Java. I can work on it right?

**Comment by Danushka96** [comment]
@pnqphong 
Yes, you can work on this,
