### ISSUE TITLE
Package Manager support

### ISSUE THREAD

**Issue by whizsid** [FOSS-UCSC/FOSSALGO#81]
#### This issue is about all algorithms

- [x] Issue Title is in form `[Algo/DS Name] in [Language]`.
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This Algo/DS is worth adding to this repository.
- [ ] Assign this issue to me (I want to work on this).
- [ ] I ensure that I am not already assigned to 2 or more issues.
- [ ] I will send my PR only after I'm assigned to this issue by any maintainer.
- [x] I understand that I will be unassigned from this issue if I fail to send a PR for this within a week.

I think the current directory structure is not good for multi-lang projects. We can separate each language with a directory

## My suggestion

```
python\
--src\
----algo_one
----algo_two
java\
--src\
----algo_one
----algo_two
```
After that, we can publish the whole `python` directory to pip and java directory to Jitpack. And we can enable users to install these algorithms via favorite package managers.

**Comment by Danushka96** [comment]
Nice!! Can you work on this?
