### ISSUE TITLE
Longest Increasing Subsequence in C++

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#815]
This is an open issue for the Longest Increasing Subsequence algorithm implementation in C++. If you wish to contribute, just make some noise and we will assign you.

**Comment by noobcoder1211** [comment]
please assign this to me i can do it in N*LOG(N) that is efficient than most people do it in O(N^2)

**Comment by Danushka96** [comment]
@noobcoder1211 
Great! please read the contribution guidelines first!

**Comment by sourabhjain9887** [comment]
please assign this issue to me.

**Comment by Danushka96** [comment]
Hi @sourabhjain9887 
This issue is already assigned,
