### ISSUE TITLE
Coin Change Problem in Python3

### ISSUE THREAD

**Issue by vivekshah1801** [FOSS-UCSC/FOSSALGO#823]
#### This issue is about [Algo/DS Name](link to resource for the Algo/DS)

-   [x] Issue Title is in form `[Algo/DS Name] in [Language]` (ex:- BubbleSort in Java)

-   [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate

-   [x] Assign this issue to me (I want to work on this)

   -   [x] I ensure that I am not already assigned to 2 or more issues
  
-   [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by vivekshah1801** [comment]
@Danushka96

**Comment by Danushka96** [comment]
Hi @vivekshah1801 
It's already there, Readme file is not updated, you can contribute to update readme file,
[https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-cochprb/python3](https://github.com/FOSS-UCSC/FOSSALGO/tree/master/algorithms/ar-cochprb/python3)

**Comment by Danushka96** [comment]
#573
