### ISSUE TITLE
Linear search in Python3 

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FOSSALGO#836]
This is an open issue for the Linear search algorithm implementation in Python3. If you wish to contribute, just make some noise and we will assign you.

**Comment by jashlodhavia** [comment]
Hey, I am willing to contribute. Can you assign the issue to me?

**Comment by jashlodhavia** [comment]
Hey Ravindu, I have completed this. https://github.com/FOSS-UCSC/FOSSALGO/pull/839 Please check this and let me know if anything else is required. Thanks
