### ISSUE TITLE
Queue in C#

### ISSUE THREAD

**Issue by Danushka96** [FOSS-UCSC/FOSSALGO#861]
This is an open issue for implementing Queue data structure in C#. If you wish to contribute, just make some noise and we will assign you.

**Comment by EstablishedShark** [comment]
id like to take this up

**Comment by NuclearCactus** [comment]
Hey @Danushka96 I want to work on this issue. Can you please assign it to me?

**Comment by RavinduSachintha** [comment]
@NuclearCactus make sure to follow the guidelines.
happy coding !!!
