### ISSUE TITLE
Doubly linked list in python

### ISSUE THREAD

**Issue by ppkavinda** [FOSS-UCSC/FOSSALGO#9]
This issues is about doubly linked list in python. [https://en.wikipedia.org/wiki/Doubly_linked_list](https://en.wikipedia.org/wiki/Doubly_linked_list)

- [x] Issue title form Algo/DS Name [Language]

- [x] I searched or browsed the repo's other issues to ensure this is not a duplicate

- [x] This Algo/DS is worth to add this repository

- [x] Assign this issue to me

- [x] I will send my PR only after I'm assigned to this issue by any maintainer

**Comment by RavinduSachintha** [comment]
After you finish your remaining and assigned issues, We will assign you for this.
